# Generated by Django 3.1.1 on 2020-09-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name_plural': 'Developer'},
        ),
        migrations.AddField(
            model_name='developer',
            name='resume',
            field=models.FileField(default='1', upload_to='uploads/resume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/developer'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(upload_to='uploads/projects'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(upload_to='uploads/skills'),
        ),
    ]
